per_page: 10
admin:
  true: "Admin"
  false: "Simple User"
actions:
  new_action: "new"
  edit: "Edit"
post_status:
  draft: "draft"
  pending: "pending"
  published: "published"
commit:
  save_draft: "Save Draft"
  publish: "Publish now"
  unpublish: "Unpublish"
  schedule: "Schedule"
  preview: "Preview"
